import Head from 'next/head'
import Link from 'next/link'
import { useQuery } from "urql";
import {PRODUCT_QUERY} from '../lib/query';
import Products from '../components/Products';
import { Gallery } from '../styles/Gallery';
import { Description } from '../styles/pageDescription';
import { Input } from '../styles/Input';
import {useState} from 'react'


export default function Home() {
  //Fetch products from strapi
  const [results] = useQuery({query: PRODUCT_QUERY });
  const {data, fetching, error} = results;
  const [searchTerm, setSearchTerm] = useState('');
  
  // check for incoming data
if(fetching) return <p>Loading...</p>
if(error) return <p>Oh no...</p>
const products = data.products.data;
console.log(products);
  return (
    <div>
      <Head>
        <title>Man Expeditions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Crimson+Pro"/>
      </Head>

      <main>
        <body>
        </body>
        <Description>
            <h1>Welcome to Man Expeditions</h1>
            <h3>Explore Global Experiences</h3>
            <h5>Get matched with like-minded travel buddies, and create extraordinary memories.</h5>
            <Input>
              <input className="center-block" type="text" placeholder="Search Your Next Trip..." onChange={(event)=>{setSearchTerm(event.target.value);}}/>
            </Input>
        </Description>
        <Gallery>
          {/* search function */}
          {products.filter((product)=> {
            if(searchTerm == ""){
              return product
            } else if (product.attributes.description.toLowerCase().includes(searchTerm.toLowerCase())){
              return product
            } else if (product.attributes.title.toLowerCase().includes(searchTerm.toLowerCase())){
              return product
            }
          }).map((product) => (
            <Products key={product.attributes.slug} product = {product}/>
          ))}
        </Gallery>
      </main>

      <footer>
      </footer>
    </div>
  )
}
