import Head from 'next/head'
import Link from 'next/link'
import { useQuery } from "urql";
import {MEMBER_QUERY} from '../lib/mquery';
import Members from '../components/Members';
import { Gallery } from '../styles/Gallery';
import {useState} from 'react'

export default function Browse() {
  //Fetch products from strapi
  const [results] = useQuery({query: MEMBER_QUERY });
  const {data, fetching, error} = results;
  const [searchTerm, setSearchTerm] = useState('');
  
  // check for incoming data
if(fetching) return <p>Loading...</p>
if(error) return <p>Oh no...</p>
const members = data.members.data;
console.log(members)
  return (
    <div>
      <Head>
        <title>Man Expeditions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <input className="center-block" type="text" placeholder="Search By Tag..." onChange={(event)=>{setSearchTerm(event.target.value);}}/>
        <Gallery>
          {/* search function */}
          {members.filter((member)=> {
            if(searchTerm == ""){
              return member
            } else if (member.attributes.description.toLowerCase().includes(searchTerm.toLowerCase())){
              return member
            } else if (member.attributes.name.toLowerCase().includes(searchTerm.toLowerCase())){
              return member
            }
          }).map((member) => (
            <Members key={member.attributes.slug} member = {member}/>
          ))}
        </Gallery>
      </main>

      <footer>
      </footer>
    </div>

    
  )
}
